"""Initial schema

Revision ID: a95b1bb45125
Revises:
Create Date: 2026-09-01 22:47:59.296837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95b1bb45125'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL', 'ALLOSCHOOL', 'OTHER', 'UPLOAD', name='sourcetype'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.BLOB(length=16), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('lesson_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_chapter'), 'lessons', ['chapter'], unique=False)
    op.create_index(op.f('ix_lessons_level'), 'lessons', ['level'], unique=False)
    op.create_index(op.f('ix_lessons_subject'), 'lessons', ['subject'], unique=False)
    op.create_table('lesson_sections',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('section_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_sections_lesson_id'), 'lesson_sections', ['lesson_id'], unique=False)
    op.create_table('questions',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sections_studied', sa.JSON(), nullable=False),
    sa.Column('exercises_attempted', sa.Integer(), nullable=False),
    sa.Column('exercises_correct', sa.Integer(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_lesson_id'), 'study_sessions', ['lesson_id'], unique=False)
    op.create_table('uploads',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('upload_type', sa.Enum('PDF', 'IMAGE', 'TEXT', name='uploadtype'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=True),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_content_hash'), 'uploads', ['content_hash'], unique=True)
    op.create_table('concepts',
    sa.Column('section_id', sa.BLOB(length=16), nullable=False),
    sa.Column('concept_type', sa.Enum('DEFINITION', 'FORMULA', 'RULE', 'MEMORIZATION', 'COMMON_MISTAKE', 'WORKED_EXAMPLE', 'IMPORTANT_POINT', name='concepttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Enum('MUST_KNOW', 'SHOULD_REMEMBER', 'GOOD_TO_KNOW', name='importancelevel'), nullable=False),
    sa.Column('source_ref', sa.BLOB(length=16), nullable=True),
    sa.Column('concept_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ref'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_concept_type'), 'concepts', ['concept_type'], unique=False)
    op.create_index(op.f('ix_concepts_section_id'), 'concepts', ['section_id'], unique=False)
    op.create_table('exercises',
    sa.Column('section_id', sa.BLOB(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='exercisedifficulty'), nullable=False),
    sa.Column('has_solution', sa.Boolean(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('exercise_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_section_id'), 'exercises', ['section_id'], unique=False)
    op.create_table('notes',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('section_id', sa.BLOB(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_lesson_id'), 'notes', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_notes_section_id'), 'notes', ['section_id'], unique=False)
    op.create_table('section_progress',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('section_id', sa.BLOB(length=16), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('checklist_items_done', sa.JSON(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel'), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_progress_lesson_id'), 'section_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_section_progress_section_id'), 'section_progress', ['section_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('section_id', sa.BLOB(length=16), nullable=True),
    sa.Column('concept_id', sa.BLOB(length=16), nullable=True),
    sa.Column('exercise_id', sa.BLOB(length=16), nullable=True),
    sa.Column('bookmark_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_concept_id'), 'bookmarks', ['concept_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_exercise_id'), 'bookmarks', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_lesson_id'), 'bookmarks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_section_id'), 'bookmarks', ['section_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('exercise_id', sa.BLOB(length=16), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_attempts_exercise_id'), 'exercise_attempts', ['exercise_id'], unique=False)
    op.create_table('weak_areas',
    sa.Column('lesson_id', sa.BLOB(length=16), nullable=False),
    sa.Column('section_id', sa.BLOB(length=16), nullable=False),
    sa.Column('concept_id', sa.BLOB(length=16), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failed', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weak_areas_concept_id'), 'weak_areas', ['concept_id'], unique=False)
    op.create_index(op.f('ix_weak_areas_lesson_id'), 'weak_areas', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_weak_areas_section_id'), 'weak_areas', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weak_areas_section_id'), table_name='weak_areas')
    op.drop_index(op.f('ix_weak_areas_lesson_id'), table_name='weak_areas')
    op.drop_index(op.f('ix_weak_areas_concept_id'), table_name='weak_areas')
    op.drop_table('weak_areas')
    op.drop_index(op.f('ix_exercise_attempts_exercise_id'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_bookmarks_section_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_lesson_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_exercise_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_concept_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_section_progress_section_id'), table_name='section_progress')
    op.drop_index(op.f('ix_section_progress_lesson_id'), table_name='section_progress')
    op.drop_table('section_progress')
    op.drop_index(op.f('ix_notes_section_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_lesson_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_exercises_section_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_concepts_section_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_concept_type'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_uploads_content_hash'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_study_sessions_lesson_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_lesson_sections_lesson_id'), table_name='lesson_sections')
    op.drop_table('lesson_sections')
    op.drop_index(op.f('ix_lessons_subject'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_level'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_chapter'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('sources')
    # ### end Alembic commands ###
